# Generated by Django 3.2.13 on 2022-05-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypost',
            name='describtion',
            field=models.TextField(max_length=300),
        ),
    ]
