# Generated by Django 3.2.13 on 2022-05-14 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_gallerycategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gallery_cat', to='gallery.gallerycategory'),
        ),
    ]
