# Generated by Django 3.2.13 on 2022-05-15 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0005_auto_20220514_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerypost',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
