# Generated by Django 3.2.13 on 2022-05-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_alter_gallerypost_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypost',
            name='describtion',
            field=models.TextField(max_length=400),
        ),
    ]
