# Generated by Django 3.2.13 on 2022-05-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20220515_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='hidden',
            field=models.BooleanField(default=True),
        ),
    ]
