# Generated by Django 3.2.13 on 2022-05-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='catgory',
            new_name='category',
        ),
    ]
