# Generated by Django 3.2.13 on 2022-05-16 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='replay_to',
            new_name='replay',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_reply',
        ),
    ]
